"""Assemble the Phase 7 submission packet (Markdown + optional PDF).

PDF section order (assignment):
1. Requirements doc & policy definitions
2. Terminal screenshot of Phase 3 handshake (placeholder image if missing)
3. Full MCP server implementation code
4. Unit test suite code and passing terminal logs
5. Agent code (MCP client + ReAct loop)
6. Verbatim traces for all 4 graded cases
7. Reflection step log
8. Screenshot of green CI pipeline (placeholder image if missing)
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_DIR = ROOT / "submission"
ASSETS = ROOT / "docs" / "submission_assets"


def _read(path: Path) -> str:
    if not path.exists():
        return f"[MISSING FILE: {path.relative_to(ROOT)}]\n"
    return path.read_text(encoding="utf-8")


def _fence(lang: str, body: str) -> str:
    return f"```{lang}\n{body.rstrip()}\n```\n"


def capture_pytest_log(dest: Path) -> Path:
    dest.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        [sys.executable, "-m", "pytest", "test_business_logic.py", "-v"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    log = (proc.stdout or "") + (proc.stderr or "")
    dest.write_text(log, encoding="utf-8")
    if proc.returncode != 0:
        raise SystemExit(f"pytest failed; see {dest}")
    return dest


def build_markdown(pytest_log: Path) -> str:
    parts: list[str] = []
    parts.append("# IT Equipment Request Lab — Submission Packet\n")
    # parts.append(
    #     "Generated by `assemble_submission.py`. Insert screenshot PNGs under "
    #     "`docs/submission_assets/` before building the final PDF for grading.\n"
    # )

    # 1
    parts.append("\n## 1. Requirements doc & policy definitions\n")
    parts.append(_read(ROOT / "docs" / "requirements.md"))

    # 2
    parts.append("\n## 2. Minimal one-tool + full-server MCP handshake\n")
    parts.append(
        "Suggested Approach step 3 — trivial `ping` server/client before business logic:\n"
    )
    minimal_png = ASSETS / "minimal_handshake.png"
    minimal_txt = ASSETS / "minimal_handshake.txt"
    if minimal_png.exists():
        parts.append(f"![Minimal one-tool MCP handshake]({minimal_png.as_posix()})\n")
    if minimal_txt.exists():
        parts.append(_fence("text", _read(minimal_txt)))
    parts.append(
        "Full equipment server handshake (`python test_client.py`):\n"
    )
    handshake = ASSETS / "phase3_handshake.png"
    handshake_txt = ASSETS / "phase3_handshake.txt"
    if handshake.exists():
        parts.append(f"![Phase 3 MCP handshake]({handshake.as_posix()})\n")
    elif handshake_txt.exists():
        parts.append(_fence("text", _read(handshake_txt)))
    else:
        parts.append(
            f"**TODO:** Save a terminal screenshot of `python test_client.py` "
            f"(tools list + EMP-101 payload) to `{handshake.relative_to(ROOT)}`.\n"
        )
        parts.append(
            "Until then, recreate the handshake with:\n\n"
            + _fence(
                "bash",
                "source .venv/bin/activate\n"
                "python examples/minimal_client.py\n"
                "python test_client.py",
            )
        )

    # 3
    parts.append("\n## 3. Full MCP server implementation\n")
    parts.append(_fence("python", _read(ROOT / "server.py")))

    # 4
    parts.append("\n## 4. Unit test suite and passing terminal logs\n")
    parts.append("### `test_business_logic.py`\n")
    parts.append(_fence("python", _read(ROOT / "test_business_logic.py")))
    parts.append("### pytest terminal log\n")
    parts.append(_fence("text", _read(pytest_log)))

    # 5
    parts.append("\n## 5. Agent code (MCP client connection + ReAct loop)\n")
    parts.append("### `agent.py`\n")
    parts.append(_fence("python", _read(ROOT / "agent.py")))
    parts.append("### `llm.py`\n")
    parts.append(_fence("python", _read(ROOT / "llm.py")))
    parts.append("### `prompts.py`\n")
    parts.append(_fence("python", _read(ROOT / "prompts.py")))

    # 6
    parts.append("\n## 6. Verbatim traces (4 graded scenarios)\n")
    for name, title in [
        ("01_approve.txt", "Clear Approval"),
        ("02_deny.txt", "Clear Denial"),
        ("03_escalate_damage.txt", "Escalation A — early + damage"),
        ("04_escalate_nonstandard.txt", "Escalation B — non-standard item"),
    ]:
        parts.append(f"\n### {title} (`traces/scenarios/{name}`)\n")
        parts.append(_fence("text", _read(ROOT / "traces" / "scenarios" / name)))

    # 7
    parts.append("\n## 7. Reflection step log\n")
    parts.append(
        "Reflection correction demo (injected bad draft → corrected decision):\n"
    )
    parts.append(
        _fence(
            "text",
            _read(ROOT / "traces" / "scenarios" / "00_reflection_correction.txt"),
        )
    )
    parts.append(
        "Additional reflection validation also appears inside each scenario trace "
        "under the `=== Reflection ===` sections.\n"
    )

    # 8
    parts.append("\n## 8. Green CI pipeline (screenshot)\n")
    ci_shot = ASSETS / "ci_green.png"
    if ci_shot.exists():
        parts.append(f"![Green CI pipeline]({ci_shot.as_posix()})\n")
    else:
        parts.append(
            f"**TODO:** After merging/pushing and CI goes green, save a screenshot "
            f"of the GitHub Actions run to `{ci_shot.relative_to(ROOT)}`.\n"
        )
        parts.append(
            "Workflow file:\n\n"
            + _fence("yaml", _read(ROOT / ".github" / "workflows" / "ci.yml"))
        )

    return "\n".join(parts)


def _wrap_line(line: str, max_chars: int) -> list[str]:
    """Hard-wrap long lines (code/JSON) so fpdf always has room for a character."""
    if not line:
        return [""]
    if max_chars < 8:
        max_chars = 8
    return [line[i : i + max_chars] for i in range(0, len(line), max_chars)]


def _strip_md_inline(text: str) -> str:
    """Remove light markdown decoration for plain PDF body text."""
    import re

    text = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"[image: \1]", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = text.replace("**", "").replace("__", "").replace("`", "")
    return text


def write_pdf_from_markdown(md_path: Path, pdf_path: Path) -> bool:
    """Readable PDF via fpdf2 (no pandoc). Renders headings/body/code with Unicode fonts."""
    try:
        from fpdf import FPDF  # type: ignore
    except ImportError:
        print("fpdf2 not installed — skipping PDF. Run: pip install fpdf2")
        return False

    font_dir = Path("/usr/share/fonts/truetype/dejavu")
    sans = font_dir / "DejaVuSans.ttf"
    sans_bold = font_dir / "DejaVuSans-Bold.ttf"
    mono = font_dir / "DejaVuSansMono.ttf"
    if not (sans.exists() and mono.exists()):
        print("DejaVu fonts not found under /usr/share/fonts/truetype/dejavu")
        return False

    text = md_path.read_text(encoding="utf-8")

    class SubmissionPDF(FPDF):
        def footer(self) -> None:
            self.set_y(-12)
            self.set_font("Sans", size=8)
            self.set_text_color(100, 100, 100)
            self.cell(0, 8, f"Page {self.page_no()}", align="C")

    pdf = SubmissionPDF(format="Letter")
    pdf.set_margins(left=14, top=14, right=14)
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_font("Sans", "", str(sans))
    pdf.add_font("Sans", "B", str(sans_bold if sans_bold.exists() else sans))
    pdf.add_font("Mono", "", str(mono))
    pdf.add_page()

    usable = pdf.epw
    in_code = False
    code_lang = ""

    def write_body(line: str, size: int = 10) -> None:
        pdf.set_font("Sans", size=size)
        pdf.set_text_color(20, 20, 20)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(
            w=usable,
            h=5,
            text=_strip_md_inline(line) if line else " ",
            new_x="LMARGIN",
            new_y="NEXT",
        )

    def write_heading(line: str, level: int) -> None:
        sizes = {1: 16, 2: 13, 3: 11}
        pdf.ln(3 if level > 1 else 2)
        pdf.set_font("Sans", "B", size=sizes.get(level, 11))
        pdf.set_text_color(10, 10, 10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(
            w=usable,
            h=7,
            text=line,
            new_x="LMARGIN",
            new_y="NEXT",
        )
        pdf.ln(1)

    def write_code_line(line: str) -> None:
        pdf.set_font("Mono", size=7)
        pdf.set_text_color(30, 30, 30)
        char_w = pdf.get_string_width("M") or 1.4
        max_chars = max(48, int(usable / char_w) - 1)
        for chunk in _wrap_line(line, max_chars):
            pdf.set_x(pdf.l_margin)
            # Light background bar for code readability
            y = pdf.get_y()
            pdf.set_fill_color(245, 245, 245)
            pdf.rect(pdf.l_margin, y, usable, 3.8, style="F")
            pdf.multi_cell(
                w=usable,
                h=3.8,
                text=chunk if chunk else " ",
                new_x="LMARGIN",
                new_y="NEXT",
            )

    def maybe_embed_image(line: str) -> bool:
        import re

        m = re.search(r"!\[[^\]]*\]\(([^)]+)\)", line)
        if not m:
            return False
        img_path = Path(m.group(1))
        if not img_path.is_absolute():
            img_path = (ROOT / img_path).resolve()
        if not img_path.exists():
            write_body(f"[Missing image: {m.group(1)}]")
            return True
        try:
            pdf.ln(2)
            pdf.image(str(img_path), w=min(usable, 170))
            pdf.ln(2)
        except Exception as exc:  # noqa: BLE001
            write_body(f"[Could not embed image {img_path.name}: {exc}]")
        return True

    for raw in text.splitlines():
        line = raw.rstrip("\n")

        if line.startswith("```"):
            if in_code:
                in_code = False
                code_lang = ""
                pdf.ln(2)
            else:
                in_code = True
                code_lang = line[3:].strip()
                pdf.ln(1)
                if code_lang:
                    pdf.set_font("Sans", size=8)
                    pdf.set_text_color(90, 90, 90)
                    pdf.multi_cell(
                        w=usable,
                        h=4,
                        text=f"[{code_lang}]",
                        new_x="LMARGIN",
                        new_y="NEXT",
                    )
            continue

        if in_code:
            write_code_line(line)
            continue

        if maybe_embed_image(line):
            continue

        if line.startswith("# "):
            write_heading(line[2:].strip(), 1)
        elif line.startswith("## "):
            write_heading(line[3:].strip(), 2)
        elif line.startswith("### "):
            write_heading(line[4:].strip(), 3)
        elif line.strip() == "---":
            pdf.ln(1)
            pdf.set_draw_color(180, 180, 180)
            y = pdf.get_y()
            pdf.line(pdf.l_margin, y, pdf.l_margin + usable, y)
            pdf.ln(3)
        elif line.startswith("|") and set(line.replace("|", "").strip()) <= {"-", ":"}:
            continue  # skip markdown table separators
        elif not line.strip():
            pdf.ln(2)
        else:
            write_body(line)

    pdf.output(str(pdf_path))
    return True


def main() -> None:
    parser = argparse.ArgumentParser(description="Assemble Phase 7 submission packet")
    parser.add_argument(
        "--skip-pytest",
        action="store_true",
        help="Reuse existing pytest log if present",
    )
    parser.add_argument(
        "--pdf",
        action="store_true",
        help="Also write a simple PDF (requires fpdf2)",
    )
    args = parser.parse_args()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    ASSETS.mkdir(parents=True, exist_ok=True)

    # Ensure placeholder notes exist for screenshot drop-in.
    for name, blurb in [
        (
            "README.md",
            "# Submission assets\n\n"
            "Place screenshots here before final PDF export:\n\n"
            "- `phase3_handshake.png` — `python test_client.py` showing tools + EMP-101\n"
            "- `ci_green.png` — green GitHub Actions CI run\n",
        ),
    ]:
        readme = ASSETS / name
        if not readme.exists():
            readme.write_text(blurb, encoding="utf-8")

    pytest_log = ASSETS / "pytest_log.txt"
    if not args.skip_pytest or not pytest_log.exists():
        print("Running pytest for submission log...")
        capture_pytest_log(pytest_log)
    else:
        print(f"Reusing {pytest_log}")

    md = build_markdown(pytest_log)
    md_path = OUT_DIR / "IT_Equipment_MCP_Submission.md"
    md_path.write_text(md, encoding="utf-8")
    print(f"Wrote {md_path}")

    if args.pdf:
        pdf_path = OUT_DIR / "IT_Equipment_MCP_Submission.pdf"
        if write_pdf_from_markdown(md_path, pdf_path):
            print(f"Wrote {pdf_path}")
        else:
            print(
                "Markdown packet is ready. Install fpdf2 or convert with pandoc:\n"
                f"  pandoc {md_path} -o {pdf_path}"
            )


if __name__ == "__main__":
    main()
